backend:
  name: git-gateway

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "rooms"
    label: "Chambres"
    files:
      - file: "content/rooms.json"
        label: "Liste des chambres"
        name: "rooms"
        fields:
          - label: "Chambres"
            name: "rooms"
            widget: "list"
            fields:
              - { label: "Nom", name: "name", widget: "string" }
              - { label: "Statut", name: "status", widget: "select", options: ["Disponible","Bientôt disponible","Louée"] }
              - { label: "Surface (m²)", name: "sqm", widget: "number" }
              - { label: "Loyer €/mois CC", name: "rent", widget: "number" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Image principale", name: "cover", widget: "image" }
              - label: "Photos"
                name: "photos"
                widget: "list"
                field: { label: "Image", name: "image", widget: "image" }

